const {test}=require('node:test');
const assert=require('node:assert/strict');
const P=require('./presentation.js');
const now=Date.parse('2026-09-27T00:00:00Z'), date=new Date(now).toISOString();
const prop={status:'read',last_success:date};
function fixture(){return {summary:{metadata_complete:true,metadata_interval:1800,last_bacnet_success:date,stale_after:180},objects:[{key:'analog-input_1',object_type:'analog-input',object_instance:1,raw_value:20,display_value:20,available:true,last_read:date,metadata_reads:{statusFlags:prop},status_flags:[0,0,0,0]},{key:'event-enrollment_1',object_type:'event-enrollment',metadata:{eventState:0,notificationClass:1},metadata_reads:{eventState:prop}},{object_type:'notification-class',object_instance:1,object_name:'URGENT',metadata:{notificationClass:1,priority:[1,2,3]}}]};}
test('freshness uses configured limit and never revives unavailable values',()=>{const r=fixture().objects[0];assert(P.fresh(r,{stale_after:600},now+200000));assert(!P.fresh(r,{stale_after:180},now+200000));r.available=false;assert(!P.fresh(r,{stale_after:600},now));});
test('unknown labels remain raw and values are formatted only for display',()=>{assert.equal(P.value({display_value:7}),'7');assert.equal(P.value({display_value:'Arrêt CPO'}),'Arrêt CPO');assert.equal(P.value({display_value:null}),'Non lue');assert.equal(P.value({display_value:21.456}),'21,46');});
test('global status never infers occupancy or a normal building',()=>{assert.equal(P.globalState(fixture(),now).label,'Données disponibles');const d=fixture();d.objects=d.objects.filter(r=>r.object_type!=='event-enrollment');assert.equal(P.globalState(d,now).label,'Observation partielle');});
test('stale event state cannot claim no active alarm',()=>{const d=fixture();d.objects[1].metadata_reads.eventState={status:'read',last_success:new Date(now-1900000).toISOString()};assert.equal(P.alarmEvidence(d,now).unknown,1);assert.equal(P.globalState(d,now).label,'Observation partielle');});
test('non-normal event uses actual notification class and priorities',()=>{const d=fixture();d.objects[1].metadata.eventState=3;const a=P.alarmEvidence(d,now);assert.equal(a.active.length,1);assert.equal(a.active[0].className,'URGENT');assert.deepEqual(a.active[0].priority,[1,2,3]);assert.equal(P.globalState(d,now).label,'Signalement CPO');});
test('in-alarm flag is independent of binary ON semantics',()=>{const d=fixture();d.objects[0].status_flags=[1,0,0,0];assert.equal(P.alarmEvidence(d,now).flags.length,1);d.objects[0].status_flags=[0,0,0,0];d.objects[0].raw_value=1;assert.equal(P.alarmEvidence(d,now).flags.length,0);});
test('connection loss supersedes cached normal state',()=>{assert.equal(P.globalState(fixture(),now+181000).label,'Communication à vérifier');});
test('explorer filters preserve raw identifiers and issue evidence',()=>{const d=fixture();assert.equal(P.filters(d.objects,{query:'analog-input_1'},d.summary,now).length,1);assert.equal(P.filters(d.objects,{issue:true},d.summary,now).length,0);d.objects[0].read_error='TimeoutError';assert.equal(P.filters(d.objects,{issue:true},d.summary,now).length,1);});
test('structured annotations use exact local references and omit ambiguous labels',()=>{const d={device_instance:130,objects:[{object_type:'structured-view',metadata:{subordinateList:[{'object-identifier':'analog-input,1','device-identifier':'device,130'},{'object-identifier':'analog-input,2','device-identifier':'device,99'},{'object-identifier':'analog-input,3'},{'object-identifier':'analog-input,3'}],subordinateAnnotations:['Texte CPO','Remote','A','B']}}]};assert.deepEqual([...P.annotations(d)],[['analog-input_1','Texte CPO']]);});
